version: '3.8'

networks:
  base:


services:
  base:
    build:
      context: ${PWD}/infra
      dockerfile: Dockerfile
    image: tuannda/base:wp
    container_name: base
    restart: always
    ports:
      - 8080:80
    volumes:
      - ${PWD}/:/var/www/html/base
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - base
  redis:
    image: redis:alpine
    restart: always
    networks:
      - base
