version: '3.8'

networks:
  base:


services:
  proxy:
    image: nginx:stable-alpine-slim
    container_name: proxy
    restart: always
    ports:
      - 8080:80
    volumes:
      - ${PWD}/:/var/www/html
      - ${PWD}/infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/infra/nginx/base.d:/etc/nginx/base.d
      - ${PWD}/infra/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - base
